remark: rmk
model_type: qwen3
model_name: Qwen/Qwen3-4B-Instruct-2507
dataset_name: gsm8k
dataset_path: null
max_samples: 50
dataloader_seed: 42
learning_rate: 0.0001
batch_size: 1
num_epochs: 50
gradient_accumulation_steps: 16
num_generations: 2
max_prompt_length: 256
max_generate_length: 256
beta: 0.1
clip_eps: 0.2
load_in_4bit: true
compute_dtype: bfloat16
use_flash_attention: true
use_gradient_checkpointing: true
device_map: auto
use_wandb: true
wandb_project: grpo-qwen3-experiments
wandb_tags:
- bs1
- lr1e-5
- ng2
- ga4
- seed42
- qwen3
- gsm8k
output_dir: /home/hula0401/learning_llm/training_with_unsloth/output/qwen3_grpo_bs1_lr1e-5_ng2_ga4_seed42_rmk
logs_dir: /home/hula0401/learning_llm/training_with_unsloth/logs/qwen3_grpo_bs1_lr1e-5_ng2_ga4_seed42_rmk
random_seed: 42
